import '../components/text-block/text-block.js';
import '../components/modal/modal.js';
import '../components/contact-screen/contact-screen.js';
import '../components/map/map.js';
import '../components/siema/siema.js';
import '../components/about-screen/about-screen.js';
import '../components/image-text-block/image-text-block.js';
import '../components/service-item/service-item.js';
import '../components/services-screen/services-screen.js';
import '../components/section/section.js';
import '../components/action-button/action-button.js';
import '../components/main-container/main-container.js';
import '../components/title-screen/title-screen.js';
import '../components/main-menu/main-menu'
import '../components/contact-panel/contact-panel'
