import '../components/scroll/scroll.css';
import '../components/scroll/scroll.js';
import '../css/variables.css'
import '../css/style.css'
import '../css/base.css'

import '../components/text-block/text-block.js';
import '../components/text-block/text-block.css';
import '../components/modal/modal.js';
import '../components/modal/modal.css';
import '../components/contact-screen/contact-screen.js';
import '../components/contact-screen/contact-screen.css';
import '../components/map/map.js';
import '../components/map/map.css';
import '../components/siema/siema.js';
import '../components/siema/siema.css';
import '../components/about-screen/about-screen.js';
import '../components/about-screen/about-screen.css';
import '../components/image-text-block/image-text-block.js';
import '../components/image-text-block/image-text-block.css';
import '../components/service-item/service-item.js';
import '../components/service-item/service-item.css';
import '../components/services-screen/services-screen.js';
import '../components/services-screen/services-screen.css';
import '../components/section/section.js';
import '../components/section/section.css';
import '../components/action-button/action-button.js';
import '../components/action-button/action-button.css';
import '../components/main-container/main-container.js';
import '../components/main-container/main-container.css';
import '../components/title-screen/title-screen.js';
import '../components/title-screen/title-screen.css';
import '../components/main-menu/main-menu.js'
import '../components/main-menu/main-menu.css'
import '../components/contact-panel/contact-panel.js'
import '../components/contact-panel/contact-panel.css'
