export const EVENT_SHOW_MODAL = 'SHOW_MODAL'
export const EVENT_HIDE_MODAL = 'HIDE_MODAL'
export const EVENT_CLOSE_MOBILE_MENU = 'CLOSE_MOBILE_MENU'

export const EVENT_INIT_ACTIONS_BUTTONS = 'INIT_ACTIONS_BUTTONS'
